### ISSUE TITLE
Initial setup not working as expected

### ISSUE THREAD

**Issue by AvnerCohen** [mcguirepr89/BirdNET-Analyzer-Pi#5]
Following up on this thread:
https://github.com/mcguirepr89/BirdNET-Pi/discussions/184#discussioncomment-3027309

I have started the work from scratch.
Clean RaspperyPi Invoking the setup instructions: https://github.com/mcguirepr89/BirdNET-Analyzer-Pi#setup-raspberry-pi-raspios-arm64-lite-for-testing

The result is an empty page on port :80 of the machine.

**Comment by mcguirepr89** [comment]
Howdy! Thanks for following up here -- I will try to run a test installation today and will report back with anything I find.

**Comment by mcguirepr89** [comment]
I did find that the installer doesn't install `avahi-utils` that supplies the `avahi-alias@$(hostname).local.service`, so you should manually install that (I've added it to the install dependencies):

```
sudo apt -y install avahi-utils
```
That will fix the `avahi-alias@$(hostname).local.service` for the installation

**Comment by AvnerCohen** [comment]
Thanks so much for the effort @mcguirepr89 
So I was unable to get this to work as Is, but if I updated the caddyfile to be more permissive, without a specific hostname:

```
http:// {
  root * /home/pi/BirdNET-Analyzer-Pi
  file_server browse
  reverse_proxy /stats* localhost:8501
}
```

This work.
However... :) I was hoping to see this summry page, and not the file browser:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/1297254/176247900-5ce4309f-7393-449a-af56-7bcbd7b69aad.png">

Is this or a an alternative is available anywhere?

**Comment by mcguirepr89** [comment]
Happy to help -- I'm glad you're interested in the project and are ready to start testing the new model. I recommend "Watching" this repo (or the main BirdNET-Pi) repo and you'll definitely get notified when this is out of alpha/beta testing and more closely resembles the current BirdNET-Pi interface

My best,
Patrick
